meta_product_name: "Atlantico Hub"
meta_title: "Transparent guarantee selection for investment firms"
meta_description: "Atlantico Hub was created to shed lights into the guarantee selection process."
meta_image: "atlantico_facebook_cover_photo.png"                       # should exist in `app/assets/images/`
